### ISSUE TITLE
Fails to install gnome-shell-extension 307 without using the search option

### ISSUE THREAD

**Issue by mbeichorn** [ianbrunelli/gnome-shell-extension-installer#3]
In attempting to install Dash to Dock
https://extensions.gnome.org/extension/307/dash-to-dock/

If I issue the command:

```
$ gnome-shell-extension-installer 307 3.14
```
or
```
$ gnome-shell-extension-installer 307 3.14 --yes
```

The extension apparently fails to install transparently. There are no error messages and the program returns 0.

I would expect that either there should be an error message, a non-zero return, or that the extension would install.

I was able install the extension using the search feature
```
$ gnome-shell-extension-installer -s dash-to-dock
[dash-to-dock] Performing search
Displaying 4 item(s). Page 1 of 1.

0: Dash to Dock, by michele_g 
   Versions: 3.14 3.12 3.10 3.8 3.6 3.4 3.2
1: Isolated workspaces, by julo42 
   Versions: (no version available)
2: Workspace Separation On Dash, by Bazon 
   Versions: 3.12 3.10 3.8 3.6 3.5.92 3.5.91 3.5.90 3.4
3: Hide Dash X, by edh 
   Versions: 3.14 3.12 3.10

Type "help" to get information on how to use the search.
Enter a command: 0
[Dash to Dock] Downloading extension
[Dash to Dock] Extracting extension
[Dash to Dock] Enabling extension
[Dash to Dock] Extension enabled (you may have to restart GNOME Shell)
Enter a command: exit
```

I tested and confirmed the issue on a clean install of Arch Linux
```
$ uname -a
Linux luna 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux
$ gnome-shell --version
GNOME Shell 3.14.3
```

**Comment by ianbrunelli** [comment]
Hey, thank you very much for the report, and sorry for the late answer (for some reason I'm not receiving notifications for new issues in the repo).

It was a silly mistake of mine in which I forgot to escape the periods in a regex.

Cheers, Ian.
