### ISSUE TITLE
Error installing extension

### ISSUE THREAD

**Issue by joca-bt** [ianbrunelli/gnome-shell-extension-installer#5]
When installing https://extensions.gnome.org/extension/496/show-desktop-from-overview/

```
$ gnome-shell-extension-installer -s "Show desktop from overview"
...
0
...
3.12
```

I get

```
...
/usr/bin/gnome-shell-extension-installer: line 46: [: ==: unary operator expected
...
```

**Comment by ianbrunelli** [comment]
Sorry, I somehow missed this!

It was fixed in b14f851, but was not released yet. You can grab it from `master`.
